language: java
dist: trusty
jdk:
  - oraclejdk8
script: 
 - mvn install -P test
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

after_success: 
 - mvn jacoco:report coveralls:report
 
addons:
  sonarcloud:
    organization: "abhaychandel-github"
    
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - 

cache:
  directories:
    - "$HOME/.m2/repository"
sudo: false
