language: java
dist: trusty
jdk:
  - oraclejdk8
script: 
 - mvn install -P test
 - sbt clean coverage test"

after_success: 
 - sbt coveralls

cache:
  directories:
    - "$HOME/.m2/repository"
sudo: false
