language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "abhaychandel-github"
    token:
      secure: "$SONAR_TOKEN"

jdk:
  - oraclejdk8

script:
  - if [ $TRAVIS_PULL_REQUEST == "false" ]; then
      mvn clean install;
    fi
    - if [ $TRAVIS_PULL_REQUEST != "false" ]; then
      mvn clean install -P test;
    fi
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
