language: java
dist: trusty
jdk:
  - oraclejdk8
script: 
 - mvn sonar:sonar


 
addons:
  sonarcloud:
    organization: 'abhaychandel-github'
    token:
      secure: 'd442ac6c91b02d43e6a3883259cef5e9621eef29'

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
sudo: false
