language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "abhaychandel-github"
    token:
      secure: "UWuE9ez57ZUqtluwTJocn82mOW6L24IMLc0NvKYje83+IXlqDLtR3mQkXPAk3bD+3EZaBd1Gqp0hgG7m+YkIaq1U2VAB9wPnzH+SbnMt7XSNrt0NixukoX7qW6pwdSEq1NhcPVkVMKatxzztDdUomx6pyM7xJ0gJTOp6Zpzu0YKkpYP5FBcHC4P72Yf4KudzS6PhHI4OR9QH3qmq0UHo+/yAWWVzrafFbiSKq/s5ijJqSWfoIz5SwOqcIqSvh3gMn9c3Xm8PngCDcHhY2t9z+nGk/wZP9rLO86JYyo5sWFEHD/8pc95fG3NO73j/ZaPjBl8d8W2titujIFn10S/LTtnsHEBI42il1KkT5qODAvcdgdv+MoTXUFJrpA2eFikTL4qOR9onUESBBF0+ancJNCN6AZGsOUsmX35qnMjYd/pBzDCYgpZjV4EysL/1PGAn2X8rNS6rdTJvIxoHDBaIaKjX57nfxmOqWK3YcY7poeyedTtJv5eAE5ykYTKDCfXHg49dhCUD/MshEsva75A7g+ur7tAXQGUA/fO6pF42csxS6AtaYLru64SSSwD30odQ/i54aTPzmeTa5xhhRH9v7EpEPtq5nN0jwOjZiok87Ea4m8bH5ku5Sqo2vOuMfAwqiZ15RTnoeM+p5NxdWPI6qXx2k3/EgNzLksk2K45TZpg="

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache
    