language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "abhaychandel-github" 

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.login=1827ba0fd640102e8966574ee1e494c10ec1c310

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
