language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: abhaychandel-github
    token:
      secure: N5r2AFoU1mYhXhjTcsILVgyNix+YORNZtJP7ltWWVegCpWMJqvMjqGQP71MxDprjuLFFK2OE8zfHZPLXnqkHswa5tPJtLpUI7zTNj4vEhHkuXlUfbIZc32yNZ/Cke9iwJIbw+uEKIn2njGmQQYrOlSrBPRSszpvWSJjiBFwzwo2cbl+6rZa981WRjslwpPXO5vcdKSb3yLY/w9QZo2akDhMg6ZnrsajumQh7DYoYlpAI06waM9I5jd0sS6QYdVCP6dL3TB/yfISxPVAt4+uyd/I3fpMWQ6KYltZlhIqSbHJ45AITalyEiLcz/ri+ckJGFsYMHKQIGMOrF+30qvikcMKBnI3kR821np9RhbtK0GOn7yrQp/ojcYhYbMG205hGNC99sN5NMfyyawCloUsWPPKdj7sTOLdl73TddJfMtoW1qKltqGDi7Y49m3yahL6Z3t3ijs3+vSUAiAMCLKYZFHOoXSAzwk9406o/ClaDlXbMnLSYUGSZz5tSRXPvAEDtHgJk5AIBWhYgL1wAeUOnjhNmFBGtJaeOZ17ICS7zeSAn8i9CpvwjOO2GmYkd7nzc8kmcPDLCt4L55sHlQ2xt6vv7K05jPznuNW6MdIfPvFoTnooIGdcCK9QEapMVCm0kTt+My5008a0C6xm3WLAHd7raYWx3nq9SnYugdFN/o/0=
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report
  package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
#env:
#  global:
#    secure: N5r2AFoU1mYhXhjTcsILVgyNix+YORNZtJP7ltWWVegCpWMJqvMjqGQP71MxDprjuLFFK2OE8zfHZPLXnqkHswa5tPJtLpUI7zTNj4vEhHkuXlUfbIZc32yNZ/Cke9iwJIbw+uEKIn2njGmQQYrOlSrBPRSszpvWSJjiBFwzwo2cbl+6rZa981WRjslwpPXO5vcdKSb3yLY/w9QZo2akDhMg6ZnrsajumQh7DYoYlpAI06waM9I5jd0sS6QYdVCP6dL3TB/yfISxPVAt4+uyd/I3fpMWQ6KYltZlhIqSbHJ45AITalyEiLcz/ri+ckJGFsYMHKQIGMOrF+30qvikcMKBnI3kR821np9RhbtK0GOn7yrQp/ojcYhYbMG205hGNC99sN5NMfyyawCloUsWPPKdj7sTOLdl73TddJfMtoW1qKltqGDi7Y49m3yahL6Z3t3ijs3+vSUAiAMCLKYZFHOoXSAzwk9406o/ClaDlXbMnLSYUGSZz5tSRXPvAEDtHgJk5AIBWhYgL1wAeUOnjhNmFBGtJaeOZ17ICS7zeSAn8i9CpvwjOO2GmYkd7nzc8kmcPDLCt4L55sHlQ2xt6vv7K05jPznuNW6MdIfPvFoTnooIGdcCK9QEapMVCm0kTt+My5008a0C6xm3WLAHd7raYWx3nq9SnYugdFN/o/0=
