CREATE SEQUENCE worker_seq;
/*MINVALUE 1
MAXVALUE 999999999999999
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;*/

CREATE TABLE WORKER(
id BIGINT default worker_seq.nextval NOT NULL,
booked BOOLEAN DEFAULT false,
CONSTRAINT PK_Worker PRIMARY KEY(id)
);

CREATE SEQUENCE job_seq;
/*MINVALUE 1
MAXVALUE 999999999999999
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;*/

CREATE TABLE JOB(
id BIGINT default job_seq.nextval NOT NULL,
worker_id BIGINT,
start_datetime TIMESTAMP,
end_datetime TIMESTAMP,
CONSTRAINT PK_Job PRIMARY KEY(id)
);